services:
  db:
    image: postgres:17.4
    container_name: blog-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567890
      POSTGRES_DB: blog-db
    volumes:
      - blog-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blog-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATASOURCE_URL: jdbc:postgresql://db:5432/blog-db
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: 1234567890
      JWT_SIGNERKEY: 6c2142ecf0065711f0ffb7de9f7060414b767533b653e3b09d338b06b603d697
      VALID_DURATION: 3600
      REFRESHABLE_DURATION: 36000
      ADMIN_PASSWORD: admin
      ADMIN_EMAIL: admin@gmail.com
    ports:
      - "8080:8080"

volumes:
  blog-data:
    external: true
