services:
  db:
    image: postgres:17.4
    container_name: postgres
    environment:
      POSTGRES_USER: ${DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
      POSTGRES_DB: ${DATASOURCE_DB}
    volumes:
      - blog-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATASOURCE_URL: jdbc:postgresql://172.18.0.2:5432/${DATASOURCE_DB}
      DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
      DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
      JWT_SIGNERKEY: ${JWT_SIGNERKEY}
      VALID_DURATION: ${VALID_DURATION}
      REFRESHABLE_DURATION: ${REFRESHABLE_DURATION}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
    ports:
      - "8080:8080"

volumes:
  blog-data:
    external: true
